
server:
  port: 8080

  tomcat:
    uri-encoding: UTF-8
 
spring:
  datasource:
      name: miniprogram
      url: jdbc:mysql://127.0.0.1:3306/miniprogram?useUnicode=true&characterEncoding=utf-8&useSSL=true
      username: root
      password:
      driver-class-name: com.mysql.jdbc.Driver

#  设置编码
  messages:
    encoding: utf-8
  http:
    encoding:
      charset: UTF-8
  banner:
    charset: UTF-8

mybatis:
  #mapperLocations指的路径是src/main/resources
  mapper-locations: mybatis/*.xml
#  mapper-locations: classpath: /mapper/*.xml  #注意：一定要对应mapper映射xml文件的所在路径
  type-aliases-package: per.niejun.entity  # 注意：对应实体类的路径
